import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Activity, AlertTriangle, ArrowUpRight, CircleHelp, LayoutDashboard, LogOut, Pause, Play, Radio, Settings, ShieldCheck, Users } from 'lucide-react'
import { supabase, privateChannel } from './lib/supabase'
import type { TradeEvent, TradingAccount } from './lib/types'
import './styles.css'

const nav = [['Overview', LayoutDashboard], ['Accounts', Users], ['Trade monitor', Activity], ['Risk controls', ShieldCheck], ['EA devices', Radio], ['Settings', Settings]] as const

function App() {
  const [session, setSession] = useState<{ user: { email?: string } } | null>(null)
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('')
  const [tab, setTab] = useState('Overview'); const [accounts, setAccounts] = useState<TradingAccount[]>([]); const [events, setEvents] = useState<TradeEvent[]>([]); const [stopped, setStopped] = useState(false)
  useEffect(() => { supabase.auth.getSession().then(({ data }) => setSession(data.session as never)); const { data } = supabase.auth.onAuthStateChange((_e, s) => setSession(s as never)); return () => data.subscription.unsubscribe() }, [])
  useEffect(() => { if (!session) return; void loadData(); }, [session])
  async function loadData() { const [a, e] = await Promise.all([supabase.from('trading_accounts').select('*').order('mode'), supabase.from('trade_events').select('*, trade_executions(status, execution_latency_ms, error_message, trading_accounts(label))').order('created_at', { ascending: false }).limit(12)]); if (!a.error) setAccounts(a.data as TradingAccount[]); if (!e.error) setEvents(e.data as TradeEvent[]) }
  useEffect(() => { if (!session) return; const workspace = accounts.find(a => a.mode === 'MASTER'); if (!workspace) return; const channel = privateChannel(`workspace:${workspace.id}:monitor`).on('broadcast', { event: 'trade_update' }, () => void loadData()).subscribe(); return () => { void supabase.removeChannel(channel) } }, [session, accounts.length])
  async function login(e: React.FormEvent) { e.preventDefault(); setError(''); const { error: err } = await supabase.auth.signInWithPassword({ email, password }); if (err) setError(err.message) }
  if (!session) return <main className="auth"><div className="auth-card"><div className="logo">◈</div><p className="eyebrow">MT5 COPY ENGINE</p><h1>Control your trading network.</h1><p className="muted">Secure master-to-slave execution, with every event auditable.</p><form onSubmit={login}><label>Email<input type="email" autoComplete="email" required value={email} onChange={e => setEmail(e.target.value)} /></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e => setPassword(e.target.value)} /></label>{error && <p className="error">{error}</p>}<button className="primary">Sign in <ArrowUpRight size={16} /></button></form><p className="tiny"><ShieldCheck size={13} /> Protected by Supabase Auth and row-level security</p></div></main>
  return <div className="app"><aside><div className="brand"><span className="logo small">◈</span><span>copy engine</span></div><p className="eyebrow side-label">WORKSPACE</p><nav>{nav.map(([label, Icon]) => <button className={tab === label ? 'nav active' : 'nav'} onClick={() => setTab(label)} key={label}><Icon size={17} />{label}</button>)}</nav><div className="side-bottom"><div className="help"><CircleHelp size={17} /><span>Need help?<small>Read the setup guide</small></span></div><button className="nav" onClick={() => void supabase.auth.signOut()}><LogOut size={17} />Sign out</button></div></aside><section className="content"><header><div><p className="eyebrow">{tab.toUpperCase()}</p><h2>{tab === 'Overview' ? 'Good morning, trader.' : tab}</h2></div><div className="header-actions"><span className="live-dot"><i /> System operational</span><button className={stopped ? 'stop on' : 'stop'} onClick={() => setStopped(!stopped)}>{stopped ? <Play size={15} /> : <Pause size={15} />}{stopped ? 'Resume copying' : 'Emergency stop'}</button></div></header>{stopped && <div className="alert"><AlertTriangle size={18} /><span><strong>Emergency stop is active.</strong> New copied trades are blocked. Existing positions are unchanged.</span></div>}<div className="stats"><Stat label="Network status" value="Operational" sub={`${accounts.filter(a => a.connection_status === 'ONLINE').length} accounts online`} good /><Stat label="Events today" value={String(events.length)} sub="Live activity feed" /><Stat label="Execution rate" value={events.length ? `${Math.round(events.filter(e => e.trade_executions?.every(x => x.status === 'EXECUTED')).length / events.length * 100)}%` : '—'} sub="Across connected slaves" good /><Stat label="Avg latency" value="—" sub="Awaiting telemetry" /></div><div className="grid"><div className="panel wide"><div className="panel-head"><div><p className="eyebrow">CONNECTED ACCOUNTS</p><h3>Trading network</h3></div><button className="ghost" onClick={() => setTab('Accounts')}>Manage accounts <ArrowUpRight size={14} /></button></div>{accounts.length ? <div className="accounts">{accounts.map(a => <Account key={a.id} account={a} />)}</div> : <Empty text="No MT5 accounts connected yet." action="Connect master EA" />}</div><div className="panel"><div className="panel-head"><div><p className="eyebrow">REALTIME FEED</p><h3>Latest events</h3></div><Radio size={17} className="purple" /></div>{events.length ? <div className="feed">{events.slice(0, 6).map(e => <div className="feed-row" key={e.id}><span className="event-icon">↗</span><div><strong>{e.action.replaceAll('_', ' ')}</strong><small>{e.symbol} · {e.volume.toFixed(2)} lot</small></div><span className="event-time">{new Date(e.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span></div>)}</div> : <Empty text="Trade events will appear here." />}</div></div></section></div>
}
function Stat(p: { label: string; value: string; sub: string; good?: boolean }) { return <div className="stat"><p className="eyebrow">{p.label}</p><strong>{p.value}</strong><small className={p.good ? 'good' : ''}>{p.good && <i />} {p.sub}</small></div> }
function Account({ account: a }: { account: TradingAccount }) { const online = a.connection_status === 'ONLINE'; return <div className="account"><div className="account-main"><span className={online ? 'status online' : 'status offline'}><i /></span><div><strong>{a.label}</strong><small>{a.mode} · {a.broker ?? 'Broker pending'}{a.server ? ` · ${a.server}` : ''}</small></div></div><div className="account-metric"><small>Balance</small><strong>${a.balance.toLocaleString()}</strong></div><div className="account-metric"><small>Equity</small><strong>${a.equity.toLocaleString()}</strong></div><span className={a.copy_status === 'ACTIVE' ? 'pill green' : 'pill amber'}>{a.copy_status}</span><button className="icon-button" aria-label="Account settings"><Settings size={16} /></button></div> }
function Empty({ text, action }: { text: string; action?: string }) { return <div className="empty"><Activity size={22} /><span>{text}</span>{action && <button className="primary compact">{action}</button>}</div> }

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)
