create extension if not exists pgcrypto;
create type public.account_mode as enum ('MASTER','SLAVE');
create type public.copy_status as enum ('ACTIVE','PAUSED','DISABLED');
create type public.trade_status as enum ('RECEIVED','VALIDATING','EXECUTING','EXECUTED','FAILED','SKIPPED');
create type public.trade_action as enum ('OPEN_MARKET','CLOSE_MARKET','PARTIAL_CLOSE','MODIFY_SL','MODIFY_TP','MODIFY_SL_TP','CREATE_PENDING','MODIFY_PENDING','DELETE_PENDING');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, display_name text, created_at timestamptz not null default now());
create table public.workspaces(id uuid primary key default gen_random_uuid(), name text not null default 'My workspace', owner_id uuid not null references auth.users(id) on delete cascade, emergency_stop boolean not null default false, max_accounts integer not null default 20 check (max_accounts > 0), created_at timestamptz not null default now());
create table public.workspace_members(workspace_id uuid references public.workspaces(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, role text not null default 'owner' check(role in ('owner','admin','operator','viewer')), created_at timestamptz not null default now(), primary key(workspace_id,user_id));
create table public.pairing_keys(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, key_hash text not null unique, key_hint text not null, revoked_at timestamptz, expires_at timestamptz, created_at timestamptz not null default now());
create table public.trading_accounts(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, label text not null, mode public.account_mode not null, broker text, server text, account_number text, copy_status public.copy_status not null default 'ACTIVE', connection_status text not null default 'OFFLINE' check(connection_status in ('ONLINE','WARNING','OFFLINE')), balance numeric not null default 0, equity numeric not null default 0, last_heartbeat_at timestamptz, ea_version text, created_at timestamptz not null default now());
create unique index one_master_per_workspace on public.trading_accounts(workspace_id) where mode='MASTER';
create table public.ea_devices(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, account_id uuid not null unique references public.trading_accounts(id) on delete cascade, device_name text not null, credential_hash text not null unique, revoked_at timestamptz, last_seen_at timestamptz, created_at timestamptz not null default now());
create table public.account_settings(account_id uuid primary key references public.trading_accounts(id) on delete cascade, volume_mode text not null default 'MULTIPLIER' check(volume_mode in ('EXACT','FIXED','MULTIPLIER','BALANCE_RATIO','EQUITY_RATIO','RISK_PERCENT','CUSTOM')), multiplier numeric not null default 1 check(multiplier >= 0), fixed_lot numeric, max_lot numeric, max_positions integer, risk_percent numeric, reconciliation_mode text not null default 'ALERT_ONLY' check(reconciliation_mode in ('ALERT_ONLY','REPAIR','STRICT_SYNC')), updated_at timestamptz not null default now());
create table public.symbol_mappings(id uuid primary key default gen_random_uuid(), account_id uuid not null references public.trading_accounts(id) on delete cascade, master_symbol text not null, slave_symbol text not null, unique(account_id,master_symbol));
create table public.trade_events(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, event_id text not null unique, master_account_id uuid not null references public.trading_accounts(id), master_position_id text, action public.trade_action not null, symbol text not null, side text, volume numeric not null check(volume > 0), price numeric, sl numeric, tp numeric, payload jsonb not null default '{}'::jsonb, sequence_number bigint not null, event_timestamp timestamptz not null, created_at timestamptz not null default now(), unique(master_account_id,sequence_number));
create table public.trade_executions(id uuid primary key default gen_random_uuid(), event_id uuid not null references public.trade_events(id) on delete cascade, account_id uuid not null references public.trading_accounts(id), status public.trade_status not null, slave_position_id text, slave_order_id text, mapped_symbol text, requested_volume numeric, executed_volume numeric, received_at timestamptz, execution_started_at timestamptz, execution_finished_at timestamptz, execution_latency_ms integer, error_code integer, error_message text, unique(event_id,account_id));
create table public.position_mappings(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, master_account_id uuid not null references public.trading_accounts(id), master_position_id text not null, slave_account_id uuid not null references public.trading_accounts(id), slave_position_id text not null, created_at timestamptz not null default now(), unique(master_account_id,master_position_id,slave_account_id));
create table public.heartbeats(id uuid primary key default gen_random_uuid(), account_id uuid not null references public.trading_accounts(id) on delete cascade, device_id uuid references public.ea_devices(id) on delete set null, balance numeric, equity numeric, free_margin numeric, open_positions integer, terminal_connected boolean, trade_allowed boolean, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.audit_logs(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, actor_user_id uuid references auth.users(id), device_id uuid references public.ea_devices(id), action text not null, resource_type text, resource_id text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index on public.trading_accounts(workspace_id,mode); create index on public.trade_events(workspace_id,created_at desc); create index on public.trade_executions(account_id,status); create index on public.heartbeats(account_id,created_at desc); create index on public.audit_logs(workspace_id,created_at desc);
create or replace function public.is_workspace_member(w uuid) returns boolean language sql stable security invoker set search_path=public as $$ select exists(select 1 from public.workspace_members m where m.workspace_id=w and m.user_id=(select auth.uid())) $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ declare workspace_id uuid; begin insert into public.profiles(id) values(new.id) on conflict do nothing; insert into public.workspaces(owner_id) values(new.id) returning id into workspace_id; insert into public.workspace_members(workspace_id,user_id,role) values(workspace_id,new.id,'owner'); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
alter table public.profiles enable row level security; alter table public.workspaces enable row level security; alter table public.workspace_members enable row level security; alter table public.pairing_keys enable row level security; alter table public.trading_accounts enable row level security; alter table public.ea_devices enable row level security; alter table public.account_settings enable row level security; alter table public.symbol_mappings enable row level security; alter table public.trade_events enable row level security; alter table public.trade_executions enable row level security; alter table public.position_mappings enable row level security; alter table public.heartbeats enable row level security; alter table public.audit_logs enable row level security;
create policy "own profile" on public.profiles for all to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy "workspace members" on public.workspaces for all to authenticated using(public.is_workspace_member(id)) with check(owner_id=(select auth.uid()));
create policy "workspace membership" on public.workspace_members for all to authenticated using(user_id=(select auth.uid()) or public.is_workspace_member(workspace_id)) with check(user_id=(select auth.uid()));
create policy "workspace owned keys" on public.pairing_keys for all to authenticated using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));
create policy "workspace accounts" on public.trading_accounts for all to authenticated using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));
create policy "workspace devices" on public.ea_devices for all to authenticated using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));
create policy "workspace events" on public.trade_events for all to authenticated using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));
create policy "workspace positions" on public.position_mappings for all to authenticated using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));
create policy "workspace audits" on public.audit_logs for all to authenticated using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));
create policy "account settings" on public.account_settings for all to authenticated using(exists(select 1 from public.trading_accounts a where a.id=account_id and public.is_workspace_member(a.workspace_id))) with check(exists(select 1 from public.trading_accounts a where a.id=account_id and public.is_workspace_member(a.workspace_id)));
create policy "account mappings" on public.symbol_mappings for all to authenticated using(exists(select 1 from public.trading_accounts a where a.id=account_id and public.is_workspace_member(a.workspace_id))) with check(exists(select 1 from public.trading_accounts a where a.id=account_id and public.is_workspace_member(a.workspace_id)));
create policy "execution accounts" on public.trade_executions for all to authenticated using(exists(select 1 from public.trading_accounts a where a.id=account_id and public.is_workspace_member(a.workspace_id))) with check(exists(select 1 from public.trading_accounts a where a.id=account_id and public.is_workspace_member(a.workspace_id)));
create policy "account heartbeats" on public.heartbeats for all to authenticated using(exists(select 1 from public.trading_accounts a where a.id=account_id and public.is_workspace_member(a.workspace_id))) with check(exists(select 1 from public.trading_accounts a where a.id=account_id and public.is_workspace_member(a.workspace_id)));
create policy "member can receive workspace monitor" on realtime.messages for select to authenticated using ((select realtime.topic()) like 'workspace:%:monitor' and public.is_workspace_member(split_part((select realtime.topic()),':',2)::uuid));
revoke all on public.pairing_keys from anon,authenticated;
alter table public.trading_accounts replica identity full;

-- No Edge Functions are required. These RPCs are the only anonymous entry points
-- used by an EA; each validates a one-time pairing secret or a hashed device token.
create or replace function public.register_ea_device(p_pairing_key text, p_account_number text, p_broker text, p_server text, p_mode public.account_mode, p_device_name text, p_ea_version text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare k pairing_keys; a trading_accounts; raw text := encode(gen_random_bytes(32),'hex');
begin
  select * into k from pairing_keys where key_hash=encode(digest(p_pairing_key,'sha256'),'hex') and revoked_at is null and (expires_at is null or expires_at>now()) for update;
  if k.id is null then raise exception 'pairing key rejected' using errcode='28000'; end if;
  if p_mode='MASTER' and exists(select 1 from trading_accounts where workspace_id=k.workspace_id and mode='MASTER') then raise exception 'workspace already has a master' using errcode='23505'; end if;
  insert into trading_accounts(workspace_id,label,mode,account_number,broker,server,ea_version) values(k.workspace_id,coalesce(nullif(p_device_name,''),p_mode::text||' MT5'),p_mode,p_account_number,p_broker,p_server,p_ea_version) returning * into a;
  insert into ea_devices(workspace_id,account_id,device_name,credential_hash) values(k.workspace_id,a.id,coalesce(nullif(p_device_name,''),'MT5 EA'),encode(digest(raw,'sha256'),'hex'));
  insert into audit_logs(workspace_id,action,resource_type,resource_id,metadata) values(k.workspace_id,'device_registered','ea_device',a.id::text,jsonb_build_object('mode',p_mode,'account_number',p_account_number));
  return jsonb_build_object('device_id',a.id,'account_id',a.id,'workspace_id',k.workspace_id,'device_token',raw,'expires_in',86400);
end; $$;
grant execute on function public.register_ea_device(text,text,text,text,public.account_mode,text,text) to anon,authenticated;

create or replace function public.record_ea_heartbeat(p_device_token text, p_balance numeric, p_equity numeric, p_free_margin numeric, p_open_positions integer, p_terminal_connected boolean, p_trade_allowed boolean, p_ea_version text)
returns jsonb language plpgsql security definer set search_path=public as $$ declare d ea_devices; begin select * into d from ea_devices where credential_hash=encode(digest(p_device_token,'sha256'),'hex') and revoked_at is null; if d.id is null then raise exception 'device rejected' using errcode='28000'; end if; update trading_accounts set connection_status='ONLINE',last_heartbeat_at=now(),balance=coalesce(p_balance,0),equity=coalesce(p_equity,0),ea_version=coalesce(p_ea_version,ea_version) where id=d.account_id; insert into heartbeats(account_id,device_id,balance,equity,free_margin,open_positions,terminal_connected,trade_allowed) values(d.account_id,d.id,p_balance,p_equity,p_free_margin,p_open_positions,p_terminal_connected,p_trade_allowed); update ea_devices set last_seen_at=now() where id=d.id; return jsonb_build_object('ok',true); end; $$;
grant execute on function public.record_ea_heartbeat(text,numeric,numeric,numeric,integer,boolean,boolean,text) to anon,authenticated;

create or replace function public.publish_master_event(p_device_token text, p_event jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$ declare d ea_devices; a trading_accounts; inserted trade_events; begin select * into d from ea_devices where credential_hash=encode(digest(p_device_token,'sha256'),'hex') and revoked_at is null; if d.id is null then raise exception 'device rejected' using errcode='28000'; end if; select * into a from trading_accounts where id=d.account_id and mode='MASTER'; if a.id is null then raise exception 'master role required' using errcode='42501'; end if; insert into trade_events(workspace_id,master_account_id,event_id,master_position_id,action,symbol,side,volume,price,sl,tp,payload,sequence_number,event_timestamp) values(d.workspace_id,d.account_id,p_event->>'event_id',p_event->>'master_position_id',(p_event->>'action')::trade_action,p_event->>'symbol',p_event->>'side',(p_event->>'volume')::numeric,(p_event->>'price')::numeric,(p_event->>'sl')::numeric,(p_event->>'tp')::numeric,coalesce(p_event->'payload','{}'),(p_event->>'sequence')::bigint,to_timestamp(coalesce((p_event->>'timestamp')::double precision/1000,extract(epoch from now())))) on conflict do nothing returning * into inserted; return jsonb_build_object('ok',true,'duplicate',inserted.id is null,'event_id',p_event->>'event_id'); end; $$;
grant execute on function public.publish_master_event(text,jsonb) to anon,authenticated;

-- Broadcast after a validated event is committed; the browser is not in the hot path.
create or replace function public.broadcast_trade_event() returns trigger language plpgsql security definer set search_path=public as $$ begin perform realtime.broadcast_changes('workspace:'||new.workspace_id::text||':monitor','trade_update',jsonb_build_object('event_id',new.event_id,'sequence',new.sequence_number,'symbol',new.symbol,'action',new.action),new); return new; end; $$;
create trigger trade_event_broadcast after insert on public.trade_events for each row execute function public.broadcast_trade_event();
revoke execute on function public.broadcast_trade_event() from anon,authenticated;
revoke execute on function public.handle_new_user() from anon,authenticated;
